# Generated by Django 4.2.1 on 2023-06-06 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('numeroTelefono', models.IntegerField()),
                ('correo', models.EmailField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('nro_orden', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('id_detalle', models.CharField(max_length=150)),
                ('cod_producto', models.CharField(max_length=16)),
                ('fecha_compra', models.DateField()),
                ('fecha_despacho', models.DateField()),
                ('fecha_entrega', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
        ),
    ]
