# Generated by Django 4.2.1 on 2023-07-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudarriendo',
            name='estado',
            field=models.BooleanField(choices=[(True, 'Disponible'), (False, 'No disponible')]),
        ),
    ]
